# Generated by Django 2.2.2 on 2019-06-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_categorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('authors', models.ManyToManyField(to='base.AuthorModel')),
                ('categories', models.ManyToManyField(to='base.CategoryModel')),
            ],
        ),
    ]
